ALTER TABLE ${TABLE_PREFIX}providers ADD COLUMN created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}providers ADD COLUMN updated_by TEXT NOT NULL DEFAULT '';

ALTER TABLE ${TABLE_PREFIX}tokens ADD COLUMN created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}tokens ADD COLUMN updated_by TEXT NOT NULL DEFAULT '';

ALTER TABLE ${TABLE_PREFIX}workflows ADD COLUMN created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}workflows ADD COLUMN updated_by TEXT NOT NULL DEFAULT '';

ALTER TABLE ${TABLE_PREFIX}workflow_versions ADD COLUMN created_by TEXT NOT NULL DEFAULT '';

ALTER TABLE ${TABLE_PREFIX}triggers ADD COLUMN created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}triggers ADD COLUMN updated_by TEXT NOT NULL DEFAULT '';

ALTER TABLE ${TABLE_PREFIX}skills ADD COLUMN created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}skills ADD COLUMN updated_by TEXT NOT NULL DEFAULT '';

ALTER TABLE ${TABLE_PREFIX}variables ADD COLUMN created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}variables ADD COLUMN updated_by TEXT NOT NULL DEFAULT '';

ALTER TABLE ${TABLE_PREFIX}node_configs ADD COLUMN created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}node_configs ADD COLUMN updated_by TEXT NOT NULL DEFAULT '';
