CREATE TABLE IF NOT EXISTS ${TABLE_PREFIX}providers (
    id TEXT PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    config TEXT NOT NULL DEFAULT '{}',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
