ALTER TABLE ${TABLE_PREFIX}bot_configs ADD COLUMN access_mode TEXT NOT NULL DEFAULT 'open';
ALTER TABLE ${TABLE_PREFIX}bot_configs ADD COLUMN pending_approval INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ${TABLE_PREFIX}bot_configs ADD COLUMN allowed_users TEXT NOT NULL DEFAULT '[]';
ALTER TABLE ${TABLE_PREFIX}bot_configs ADD COLUMN pending_users TEXT NOT NULL DEFAULT '[]';
