ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN identifier TEXT DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN parent_id TEXT DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN project_id TEXT DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN billing_code TEXT DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN priority_level TEXT DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN request_depth INTEGER DEFAULT 0;
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN started_at TEXT DEFAULT NULL;
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN completed_at TEXT DEFAULT NULL;
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN cancelled_at TEXT DEFAULT NULL;
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN hidden_at TEXT DEFAULT NULL;

CREATE INDEX IF NOT EXISTS idx_${TABLE_PREFIX}tasks_identifier ON ${TABLE_PREFIX}tasks(identifier);
CREATE INDEX IF NOT EXISTS idx_${TABLE_PREFIX}tasks_parent ON ${TABLE_PREFIX}tasks(parent_id);
