ALTER TABLE ${TABLE_PREFIX}triggers ADD COLUMN alias TEXT DEFAULT NULL;
ALTER TABLE ${TABLE_PREFIX}triggers ADD COLUMN public INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS idx_${TABLE_PREFIX}triggers_alias ON ${TABLE_PREFIX}triggers(alias) WHERE alias IS NOT NULL;
