ALTER TABLE ${TABLE_PREFIX}providers ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}providers ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT '';

ALTER TABLE ${TABLE_PREFIX}tokens ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}tokens ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT '';

ALTER TABLE ${TABLE_PREFIX}workflows ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}workflows ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT '';

ALTER TABLE ${TABLE_PREFIX}workflow_versions ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT '';

ALTER TABLE ${TABLE_PREFIX}triggers ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}triggers ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT '';

ALTER TABLE ${TABLE_PREFIX}skills ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}skills ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT '';

ALTER TABLE ${TABLE_PREFIX}variables ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}variables ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT '';

ALTER TABLE ${TABLE_PREFIX}node_configs ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}node_configs ADD COLUMN IF NOT EXISTS updated_by TEXT NOT NULL DEFAULT '';
