-- Cache-aware pricing and token spend budgets.
ALTER TABLE ${TABLE_PREFIX}tokens ADD COLUMN IF NOT EXISTS spend_limit_cents DOUBLE PRECISION DEFAULT NULL;

ALTER TABLE ${TABLE_PREFIX}token_usage ADD COLUMN IF NOT EXISTS cache_read_tokens BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ${TABLE_PREFIX}token_usage ADD COLUMN IF NOT EXISTS cache_write_tokens BIGINT NOT NULL DEFAULT 0;

ALTER TABLE ${TABLE_PREFIX}model_pricing ADD COLUMN IF NOT EXISTS cache_read_price_per_1m DOUBLE PRECISION DEFAULT 0;
ALTER TABLE ${TABLE_PREFIX}model_pricing ADD COLUMN IF NOT EXISTS cache_write_price_per_1m DOUBLE PRECISION DEFAULT 0;

ALTER TABLE ${TABLE_PREFIX}cost_events ADD COLUMN IF NOT EXISTS cache_read_tokens BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ${TABLE_PREFIX}cost_events ADD COLUMN IF NOT EXISTS cache_write_tokens BIGINT NOT NULL DEFAULT 0;
