-- Source metadata for model pricing sync/import workflows.
ALTER TABLE ${TABLE_PREFIX}model_pricing ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}model_pricing ADD COLUMN IF NOT EXISTS source_provider TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}model_pricing ADD COLUMN IF NOT EXISTS source_model TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}model_pricing ADD COLUMN IF NOT EXISTS source_url TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}model_pricing ADD COLUMN IF NOT EXISTS source_prompt_price_per_1m DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE ${TABLE_PREFIX}model_pricing ADD COLUMN IF NOT EXISTS source_completion_price_per_1m DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE ${TABLE_PREFIX}model_pricing ADD COLUMN IF NOT EXISTS source_cache_read_price_per_1m DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE ${TABLE_PREFIX}model_pricing ADD COLUMN IF NOT EXISTS source_cache_write_price_per_1m DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE ${TABLE_PREFIX}model_pricing ADD COLUMN IF NOT EXISTS manual_override BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ${TABLE_PREFIX}model_pricing ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ DEFAULT NULL;
