ALTER TABLE ${TABLE_PREFIX}bot_configs ADD COLUMN IF NOT EXISTS access_mode TEXT NOT NULL DEFAULT 'open';
ALTER TABLE ${TABLE_PREFIX}bot_configs ADD COLUMN IF NOT EXISTS pending_approval BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ${TABLE_PREFIX}bot_configs ADD COLUMN IF NOT EXISTS allowed_users JSONB NOT NULL DEFAULT '[]';
ALTER TABLE ${TABLE_PREFIX}bot_configs ADD COLUMN IF NOT EXISTS pending_users JSONB NOT NULL DEFAULT '[]';
