ALTER TABLE ${TABLE_PREFIX}organizations ADD COLUMN IF NOT EXISTS issue_prefix TEXT DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}organizations ADD COLUMN IF NOT EXISTS issue_counter BIGINT DEFAULT 0;
ALTER TABLE ${TABLE_PREFIX}organizations ADD COLUMN IF NOT EXISTS budget_monthly_cents BIGINT DEFAULT 0;
ALTER TABLE ${TABLE_PREFIX}organizations ADD COLUMN IF NOT EXISTS spent_monthly_cents BIGINT DEFAULT 0;
ALTER TABLE ${TABLE_PREFIX}organizations ADD COLUMN IF NOT EXISTS budget_reset_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE ${TABLE_PREFIX}organizations ADD COLUMN IF NOT EXISTS require_board_approval_for_new_agents BOOLEAN DEFAULT FALSE;
