ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN IF NOT EXISTS identifier TEXT DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN IF NOT EXISTS parent_id TEXT DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN IF NOT EXISTS project_id TEXT DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN IF NOT EXISTS billing_code TEXT DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN IF NOT EXISTS priority_level TEXT DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN IF NOT EXISTS request_depth INTEGER DEFAULT 0;
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN IF NOT EXISTS started_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE ${TABLE_PREFIX}tasks ADD COLUMN IF NOT EXISTS hidden_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;

CREATE INDEX IF NOT EXISTS idx_${TABLE_PREFIX}tasks_identifier ON ${TABLE_PREFIX}tasks(identifier);
CREATE INDEX IF NOT EXISTS idx_${TABLE_PREFIX}tasks_parent ON ${TABLE_PREFIX}tasks(parent_id);
