ALTER TABLE ${TABLE_PREFIX}organizations ADD COLUMN IF NOT EXISTS head_agent_id TEXT DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}organizations ADD COLUMN IF NOT EXISTS max_delegation_depth INTEGER DEFAULT 10;
