ALTER TABLE ${TABLE_PREFIX}skills ADD COLUMN IF NOT EXISTS resources JSONB NOT NULL DEFAULT '[]';
ALTER TABLE ${TABLE_PREFIX}skills ADD COLUMN IF NOT EXISTS source_type TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}skills ADD COLUMN IF NOT EXISTS source_ref TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}skills ADD COLUMN IF NOT EXISTS source_path TEXT NOT NULL DEFAULT '';
ALTER TABLE ${TABLE_PREFIX}skills ADD COLUMN IF NOT EXISTS source_credential_id TEXT NOT NULL DEFAULT '';
