ALTER TABLE ${TABLE_PREFIX}triggers ADD COLUMN IF NOT EXISTS alias TEXT DEFAULT NULL;
ALTER TABLE ${TABLE_PREFIX}triggers ADD COLUMN IF NOT EXISTS public BOOLEAN NOT NULL DEFAULT FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_${TABLE_PREFIX}triggers_alias ON ${TABLE_PREFIX}triggers(alias) WHERE alias IS NOT NULL;
